<!-- content of the mainpage -->
<h1>Willkommen</h1>
<?php 
if($this->masterOnline == 1)		//if logged in
{
?>
	Sie wurden als Master angemeldet und haben nun folgende Möglichkeiten:
	<ul>
	    <li>Neues Thema erstellen</li>
	    <li>Thema überarbeiten und eine aktuellere Version erzeugen</li>
	    <li>Freunde zu ihren Themen per Email einladen bzw. Einladungen widerrufen</li>
	    <li>Kommentare schreiben und löschen</li>
	</ul>
	Auf der linken Seite finden Sie ein Suchfeld, mit dessen Hilfe Sie leicht nach Freunden bzw. Themen suchen können.
<?php 
} 
else					//if not logged in
{
?>
	<p><?php echo $this->translate( 'Auf dieser Seite können Sie verschiedene Themen mit ihren Freunden besprechen.'); ?></p>
	<p><?php echo $this->translate( 'Bitte benutzen die einen Link um zu den Themen zu gelangen,'); ?><br> 
           <?php echo $this->translate( 'oder wenn Sie der Administrator sind, melden Sie sich einfach an.'); ?></p>
<?php 
}
?>

