<!-- content for login -->
<!-- formular which navigates to login after pressing the submit button -->
<form action="login" method="post">
	<fieldset>
		<legend>LogIn</legend>	<!-- head -->
		<table>
			<tr>		<!-- username textfield -->
				<td>
					<label for="usern">Username</label>
				</td>
				<td>
					<input type="text" id="usern" name="usern" maxlength="50" value="" />
				</td>
			</tr>
			<tr>		<!-- password textfield -->
				<td>
					<label for="password">Password</label>
				</td>
				<td>
					<input type="password" id="password" name="password" maxlength="10" value="" />
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>	<!-- submit button a login request -->
					<input type="submit" name="button_save" value="einloggen" class="button" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<hr/>
