<!-- content for change the account details -->
<!-- formular which navigates to leupdate after pressing the submit button -->
<form action="leupdate" method="post">
	<fieldset>
		<legend>UpDate</legend>		<!-- head -->
		<table>
			<tr>			<!-- new username textfield -->
				<td>
					<label for="usern">New Username</label>
				</td>
				<td>
					<input type="text" id="usern" name="usern" maxlength="50" value="" />
				</td>
			</tr>
			<tr>			<!-- new password textfield -->
				<td>
					<label for="password">New Password</label>
				</td>
				<td>
					<input type="text" id="password" name="password" maxlength="10" value="" />
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>		<!-- submit button to change the account details -->
					<input type="submit" name="button_save" value="update" class="button" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<hr/>
