<!-- content for change the account details -->
<!-- formular which navigates to leupdate after pressing the submit button -->
<form action="update" method="post">
	<fieldset>
		<legend>UpDate</legend>		<!-- head -->
		<table>
	<!-- old login information -->
			<tr>			<!-- old username textfield -->
				<td>
					<label for="usern">Username</label>
				</td>
				<td>
					<input type="text" id="usern" name="usern" maxlength="50" value="" />
				</td>
			</tr>
			<tr>			<!-- old password textfield -->
				<td>
					<label for="password">Password</label>
				</td>
				<td>
					<input type="password" id="password" name="password" maxlength="10" value="" />
				</td>
			</tr>
			<tr>
				<td>
					<hr/>
				</td>
				<td>
					<hr/>
				</td>
			</tr>
	<!-- new login information -->

			<tr>			<!-- new username textfield -->
				<td>
					<label for="newUsern">New Username</label>
				</td>
				<td>
					<input type="text" id="newUsern" name="newUsern" maxlength="50" value="" />
				</td>
			</tr>
			<tr>			<!-- new password textfield -->
				<td>
					<label for="newPassword">New Password</label>
				</td>
				<td>
					<input type="password" id="newPassword" name="newPassword" maxlength="10" value="" />
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>		<!-- submit button to change the account details -->
					<input type="submit" name="button_save" value="update" class="button" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<hr/>
