<!-- content for change the account details -->
<!-- formular which navigates to leupdate after pressing the submit button -->
<p><?php echo $this->translate( 'Hier können Sie Ihren Usernamen oder Ihr Password ändern.'); ?><br>
   <?php echo $this->translate( 'Einfach entsprechendes eingeben. '); ?></p>
<p><?php echo $this->translate( 'Sie müssen sich mit Ihren alten Daten authentifizieren.'); ?></p>
<form action="update" method="post">
	<fieldset>
		<legend>UpDate</legend>		<!-- head -->
		<table>
	<!-- old login information -->
			<tr>			<!-- old username textfield -->
				<td>
					<label for="usern">Username</label>
				</td>
				<td>
					<input type="text" id="usern" name="usern" maxlength="30" value="" />
				</td>
			</tr>
			<tr>			<!-- old password textfield -->
				<td>
					<label for="password"><?php echo $this->translate( 'Passwort'); ?></label>
				</td>
				<td>
					<input type="password" id="password" name="password" maxlength="16" value="" />
				</td>
			</tr>
			<tr>
				<td>
					<hr/>
				</td>
				<td>
					<hr/>
				</td>
			</tr>
	<!-- new login information -->

			<tr>			<!-- new username textfield -->
				<td>
					<label for="newUsern"><?php echo $this->translate( 'Neuer Username'); ?></label>
				</td>
				<td>
					<input type="text" id="newUsern" name="newUsern" maxlength="30" value="" />
				</td>
			</tr>
			<tr>			<!-- new password textfield -->
				<td>
					<label for="newPassword1"><?php echo $this->translate( 'Neues Passwort'); ?></label>
				</td>
				<td>
					<input type="password" id="newPassword1" name="newPassword1" maxlength="16" value="" />
				</td>
			</tr>
			<tr>			<!-- check password textfield -->
				<td>
					<label for="newPassword2"><?php echo $this->translate( 'Passwortkontrolle'); ?></label>
				</td>
				<td>
					<input type="password" id="newPassword2" name="newPassword2" maxlength="16" value="" />
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>		<!-- submit button to change the account details -->
					<input type="submit" name="button_save" value="update" class="button" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<hr/>
