<!-- content for create a comment -->
<!-- formular which navigates to validate after pressing the submit button -->
<form action="validate" method="post">
	<input type="hidden" id="topicID" name="topicID" value="<?php echo $this->topicID; ?>" />
	<fieldset>
		<legend>Kommentar zu <?php echo $this->topicName; ?></legend> <!-- head -->
		<table>
			<colgroup>
				<!-- size of the first column -->
				<col width="80">
			</colgroup>
			<tr>				<!-- username textfield -->
				<td>
					<label for="userName">Nickname</label>
				</td>
				<td>
					<input type="text" id="userName" name="userName" maxlength="20" value="" />
				</td>
			</tr>
			<tr>				<!-- comment textfield -->
				<td>
					<label for="commentText">Kommentar</label>
				</td>
				<td>
					<textarea id="commentText" name="commentText" rows="10" maxlength="500" ></textarea>
				</td>
			</tr>
			<tr>
				<td>			<!-- button to go back -->
					<input type="button" name="button_goback" value="zurück" onClick="history.back()">
				</td>
				<td>			<!-- submit button to send the comment -->
					<input type="submit" name="button_save" value="Kommentar senden" class="button" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<hr/>
