<h2>
	<?php echo $this->escape($this->topics->topicName) ?>
</h2>
<hr/>
<?php
foreach ($this->comments as $a)
{
	echo '<fieldset>';
		echo '<legend>'. $this->escape($a->userName) .' - '. $this->escape($a->commentDate) .'</legend>';
		echo '<p>'. $this->escape($a->commentText) .'</p>';
	echo '</fieldset>';
}
?>
<table>
	<tr>
		<td>
			<form action="<?php echo $this->url(array('controller'=>'Comments', 'action'=>'create'), null, true) ?>" method="post">
				<input type="hidden" id="topicID" name="topicID" value="<?php echo $this->escape($this->topics->topicID) ?>" />
				<input type="hidden" id="topicName" name="topicName" value="<?php echo $this->escape($this->topics->topicName) ?>" />
				<input type="submit" name="button_com" value="kommentieren" class="button" />
			</form>
		</td>
		<td align="right">
			<form action="http://localhost/BComment/public/comments/show/id/<?php echo $this->escape($this->topics->topicID) ?>" method="post">
				<input type="submit" name="button_goback" value="zurück" class="button" />
			</form>
		</td>
	</tr>
</table>
<hr/>
