<!-- content of the topic view -->
<h2>
	<!-- head of the topic -->
	<?php echo $this->escape($this->topics->topicName) ?>
</h2>
<p>
	<!-- topic content (the picture) -->
	<img src="<?php echo $this->escape($this->topics->topicContent) ?>" width="100%" height="100%" alt="<?php echo $this->escape($this->topics->topicName) ?>">
</p>
<hr/>

<?php
foreach ($this->comments as $a)		//for each obtained comment
{
	echo '<fieldset>';		//give all information about the comment
		echo '<legend>'. $this->escape($a->userName) .' - '. $this->escape($a->commentDate) .'</legend>';
		echo '<p>'. $this->escape($a->commentText) .'</p>';
	echo '</fieldset>';
}
?>
<table>
	<tr>
		<td>
			<!-- formular which navigates to create after pressing the submit button -->
			<!-- with hidden information about topicID and topicName -->
			<form action="<?php echo $this->url(array('controller'=>'Comments', 'action'=>'create'), null, true) ?>" method="post">
				<input type="hidden" id="topicID" name="topicID" value="<?php echo $this->escape($this->topics->topicID) ?>" />
				<input type="hidden" id="topicName" name="topicName" value="<?php echo $this->escape($this->topics->topicName) ?>" />
				<input type="submit" name="button_com" value="kommentieren" class="button" />
			</form>
		</td>
		<td align="right">
			<!-- formular which navigates to cshow after pressing the submit button -->
			<form action="<?php echo $this->url(array('controller'=>'Comments', 'action'=>'cshow'), null, true) ?>/id/<?php echo $this->escape($this->topics->topicID) ?>" method="post">
				<input type="submit" name="button_allcom" value="alle Kommentare anschauen" class="button" />
			</form>
		</td>
	</tr>
</table>
<hr/>

