<div id = "main_Main">
<?php
    if (!empty( $this->msg))
    {
        echo $this->msg;
    }

    echo '<h1>' . $this->topicName . '</h1>';
    echo '<h2>Version :' . $this->topicVersion . '</h2>';
    echo '<form action = "validateedit" method = "post">';
        echo '<input type = "hidden" name = "topicID" value = "' . $_GET['id'] . '"/>';
        echo '<input type = "hidden" name = "topicVersion" value = "' . $this->topicVersion . '"/>';
        echo '<textarea name = "topicContent" cols = "100" rows = "20"/>' . $this->topicContent . '</textarea>';
        echo '<input type = "text" name = "topicSource" value = "' . $this->topicSource . '"/>';
        echo '<input type = "submit" value = "neue Version speichern"/>';
    echo '</form>';

?>
</div>
