<!-- content of the fiend overview and createfriend option -->

<table border = "1">
	<tr>				<!--tablehead-->
		<td>
			<?php echo $this->translate( 'Vorname'); ?>
		</td>
		<td>
			<?php echo $this->translate( 'Nachname'); ?>
		</td>
		<td>
			<?php echo $this->translate( 'E-Mail-Adresse'); ?>
		</td>
		<td>
			<?php echo $this->translate( 'Beruf'); ?>
		</td>
		<td>
			<?php echo $this->translate( 'Adresse'); ?>
		</td>
		<td>
		</td>
		<td>
		</td>
	</tr>
<?php
foreach ($this->friends as $a)		//for each friend
{
?>
	<tr>
		<td>
			<?php echo $this->escape($a->first_name) ?>
		</td>
		<td>
			<?php echo $this->escape($a->last_name) ?>
		</td>
		<td>
			<?php echo $this->escape($a->email) ?>
		</td>
		<td>
			<?php echo $this->escape($a->job) ?>
		</td>
		<td>
			<?php echo $this->escape($a->adresse) ?>
		</td>
		<td>
			<form action="<?php echo $this->url(array('controller'=>'master', 'action'=>'showfriend'), null, true) ?>?id=<?php echo $this->escape($a->userID) ?>" method="post">
				<input type="submit" name="button_send" value="<?php echo $this->translate( 'Details'); ?>" class="button" />
			</form>
		</td>
		<td>
			<form action="<?php echo $this->url(array('controller'=>'master', 'action'=>'delfriend'), null, true) ?>" method="post">
					<input type = "hidden" name = "userID" value = "<?php echo $this->escape($a->userID) ?>" />
				<input type="submit" name="button_delete_friend" value=" X " class="button" />
			</form>
		</td>
	</tr>
<?php
}
?>
</table>


<?php 
    echo $this->createFriendForm;
?>
