<!-- content of the invite overview and createfriend option -->
<form action="<?php echo $this->url(array('controller'=>'master', 'action'=>'send'), null, true) ?>" method="post">
	<table border = "1">
		<tr>				<!--tablehead-->
			<td>
				<?php echo $this->translate( 'Vorname'); ?>
			</td>
			<td>
				<?php echo $this->translate( 'Nachname'); ?>
			</td>
			<td>
				<?php echo $this->translate( 'E-Mail-Adresse'); ?>
			</td>
			<td>
				<?php echo $this->translate( 'Beruf'); ?>
			</td>
			<td>
				<?php echo $this->translate( 'einladen'); ?>
			</td>
		</tr>
	<?php
	foreach ($this->friends as $a)		//for each friend
	{
	?>
		<tr>
			<td>
				<?php echo $this->escape($a->first_name) ?>
			</td>
			<td>
				<?php echo $this->escape($a->last_name) ?>
			</td>
			<td>
				<?php echo $this->escape($a->email) ?>
			</td>
			<td>
				<?php echo $this->escape($a->job) ?>
			</td>
			<td <?php if(in_array($this->escape($a->userID),$this->infoUserIDs)){echo 'style="background-color:#FF0000"';} ?>>
				<input type="checkbox" name="<?php echo $this->escape($a->userID) ?>" value="<?php echo $this->escape($a->email) ?>">
			</td>
		</tr>
	<?php
	}
	?>
	</table>
	<input type = "hidden" name = "topicID" value = "<?php echo $this->topicID; ?>" />
	<input type="submit" name="button_send" value="<?php echo $this->translate( 'ausgewählte Freunde informieren'); ?>" class="button" />
</form>

<?php 
    echo $this->createFriendForm;
?>
