<?php
	if(count($this->resultFriend)!= 0)
	{
		if($this->resultFriend != "" && $this->resultFriend != " ")
		{
?>
			<table border = "1"> <!-- tablehead -->
				<tr>
					<td><?php echo $this->translate( 'Vorname'); ?></td>
					<td><?php echo $this->translate( 'Nachname'); ?></td>
					<td><?php echo $this->translate( 'E-Mail-Adresse'); ?></td>
					<td><?php echo $this->translate( 'Beruf'); ?></td>
					<td><?php echo $this->translate( 'Adresse'); ?></td>
					<td></td>
				</tr>
<?php
				foreach( $this->resultFriend as $a)
				{
?>
					<tr>									<!-- tablebody -->
						<td>
							<?php echo $a['first_name']; ?>
						</td>
						<td>
							<?php echo $a['last_name']; ?>
						</td>
						<td> 
							<?php echo $a['email']; ?>
						</td>
						<td> 
							<?php echo $a['job']; ?>
						</td>
						<td> 
							<?php echo $a['adresse']; ?>
						</td>
						<td>
							<form	action="<?php echo $this->url(array('controller'=>'master', 'action'=>'showfriend'), null, true) ?>?id=<?php echo $this->escape($a->userID) ?>"
								method="post">
								<input type="submit" name="button_friend" value="<?php echo $this->translate( 'Details'); ?>" class="button" />
							</form>
						</td>
					</tr>
<?php
				}
?>
			</table>
<?php
		}
	}
?>
<?php
	if(count($this->resultTopic)!= NULL)
	{
		if($this->resultTopic != "" && $this->resultTopic != " ")
		{
?>
			<table border = "1"> <!-- tablehead -->
				<tr>
					<td><?php echo $this->translate( 'Thema'); ?></td>
					<td></td>
				</tr>
<?php
				foreach( $this->resultTopic as $b)
				{
?>
					<tr>									<!-- tablebody -->
						<td>
							<?php echo $b['topicName']; ?>
						</td>
						<td>
							<form	action="<?php echo $this->url(array('controller'=>'master', 'action'=>'showtopics'), null, true) ?>?id=<?php echo $b['topicID'] ?>&ver=<?php echo $b['version'] ?>"
								method="post">
								<input type="submit" name="button_topic" value="<?php echo $this->translate( 'zum Thema'); ?>" class="button" />
							</form>
						</td>
					</tr>
<?php
				}
?>
			</table>
<?php
		}
	}
	
		echo $this->msg;
?>
