<?php
	if($this->result != "" && $this->result != " ")
	{
?>
<table border = "1"> <!-- tablehead -->
<tr>
	<td><?php echo $this->translate( 'Vorname'); ?></td>
	<td><?php echo $this->translate( 'Nachname'); ?></td>
	<td><?php echo $this->translate( 'E-Mail-Adresse'); ?></td>
	<td><?php echo $this->translate( 'Beruf'); ?></td>
	<td><?php echo $this->translate( 'Adresse'); ?></td>
</tr>
<?php
	foreach( $this->result as $a)
	{
?>
	<tr>									<!-- tablebody -->
		<td>
			<?php echo $a['first_name']; ?>
		</td>
		<td>
			<?php echo $a['last_name']; ?>
		</td>
		<td> 
			<?php echo $a['email']; ?>
		</td>
		<td> 
			<?php echo $a['job']; ?>
		</td>
		<td> 
			<?php echo $a['adresse']; ?>
		</td>
	</tr>
<?php
	}
?>
</table>
<?php
}
else
echo "<?php echo $this->translate( 'Sie müssen den Namen eines Freundes eingeben!'); ?>";
?>