<div id = "navi">
<ul>
<?php
    foreach( $this->allTopicsRowSet as $topicRow)
	{
        if ( isset( $_GET['id']))
        {
            if ( $_GET['id'] == $topicRow['topicID'])
            {
                echo '<li>aktuelles Thema</li>';
            }
            else 
            {
                echo '<li><a href="http://localhost/Webressourcen/public/master/showtopics?id='.$topicRow['topicID'] . '&ver=1">';
                echo $topicRow['topicName'].'</a></li>';
            }
        }
        else 
        {
            echo '<li><a href="http://localhost/Webressourcen/public/master/showtopics?id='.$topicRow['topicID'] . '&ver=1">';
            echo $topicRow['topicName'].'</a></li>';
        }
    }
?>
</ul>
</div>
<div id = "content">
<?php
    if ( !empty( $this->topicContent))
    {
        echo '<center><h1>';
        echo $this->topicName;
        echo '</h1></center><ul>';
        foreach( $this->topicVersionArray as $topicVersion)
        {
            if ( $this->selectedTopicVersion == $topicVersion)
            {
                echo '<li>' . $topicVersion . '</li>';
            }
            else
            {
                echo '<li><a href = "http://localhost/Webressourcen/public/master/showtopics?id=' . $_GET['id'] . '&ver=' . $topicVersion . '">';
                echo $topicVersion . '</a></li>';
            }
        }        
        echo '</ul>';
        echo $this->topicContent;
        
        if ( !empty( $this->userCommentRowSet))
        {
            echo '<table border = "1">';
            foreach( $this->userCommentRowSet as $userCommentRow)
            {
                echo '<tr><td>' . $userCommentRow['commentDate'] . '</td>';
                echo '<td>' . $userCommentRow['userName'] . '</td>';
                echo '<td>' . $userCommentRow['commentText'] . '</td></tr>';
            }
            echo '</table>';
            
            echo '<form action = "showtopics?id=' . $_GET['id'] . '&ver=' . $this->selectedTopicVersion . '&exp=' . $this->exp .'" method = "post">';
                echo '<input type = "submit" value = "' . $this->expButtonValue . '" />';
            echo '</form>';
        }
        echo '<p>' . $this->createCommentForm;
    }
?>
</div>