<script type = "text/javascript">
/**
 * asks the user if he really want to delete this friend
 *
 * @param form indicates whitch form to submit
 */
function confirmation( form)
{
    answer = confirm( '<?php echo $this->translate( 'Sind Sie sicher, dass Sie dieses Thema endgültig löschen möchten?'); ?>');
    if ( answer)
    {
        form.submit();
    }
}
</script>
<?php
    if ( !empty( $this->topicContent))
    {
        echo '<div id = "content">';
        
        echo $this->msg;  //errormessage
        echo '<center><h1>' . $this->topicName . '</h1></center>';
        
        if ( $this->topicTest)
        {
            /* dropbox with available topicVersion */
            echo '<form name = "versionSelectForm">';
            echo 'Version: <select name="versionSelect" onChange = "window.location=document.versionSelectForm.versionSelect.options[document.versionSelectForm.versionSelect.selectedIndex].value">';
    
            foreach( $this->topicVersionArray as $topicVersion)
            {
                if ( $this->selectedTopicVersion == $topicVersion)
                {
                    echo '<option selected = "selected" value = "showtopics?id=' . $_GET['id'] . '&ver=' . $topicVersion . '">' . $topicVersion . '</option>';
                }
                else
                {
                    echo '<option value = "showtopics?id=' . $_GET['id'] . '&ver=' . $topicVersion . '">' . $topicVersion . '</option>';
                }
            }        
            echo '</select></form>';
        
            /* button to close the current topic */
            echo '<form id = "closeTopicForm" action = "closetopic" method = "post">';
                echo '<input type = "hidden" name = "topicID" value = "' .  $_GET['id'] . '" />';
                echo '<input type = "button" value = "' . $this->translate( 'Thema schließen') . '" onclick = "confirmation( this.form)" />';
            echo '</form>';
            
            /* invitebutton, redirectes to the invite-page */
            echo '<form action = "invite" method = "post">';
                echo '<input type = "hidden" name = "topicID" value = "' . $_GET['id'] . '" />';
                echo '<input type = "submit" value = "' . $this->translate( 'Einladungen versenden') . '" />';
            echo '</form>';
        
            /* button to edit and create a new topicVersion */
            echo '<form action = "edittopic" method = "get">';
                echo '<input type = "hidden" name = "id" value = "' . $_GET['id'] . '" />';
                echo '<input type = "hidden" name = "ver" value = "' . $_GET['ver'] . '" />';
                echo '<input type = "submit" value = "' . $this->translate( 'Inhalt überarbeiten') . '" />';
            echo '</form>';
            
            /* iframe */
            echo $this->topicContent;
            
            echo '<p>' . $this->translate( 'Durchschnittliche Bewertung:') . ' <p><img src = "../_files/image/rating/stars/5Star_' . $this->topicRating . '.png" height = "50" alt = "' . $this->topicRating . '"';
                    
            if( $this->ratingPercent)
            {
                echo ' ."' . $this->translate( 'Sterne von 5 Sternen') . '"';
            }
            echo '>';
        }
        else 
        {
            echo $this->topicContent;
        }
        echo '</div>';
        
        /* --- commentpart --- */
        echo '<div id = "comment">';
        
        if ( !empty( $this->commentRowSet))
        {
            echo '<table border = "1">';
            foreach( $this->commentRowSet as $commentRow)
            {
                echo '<tr><td>' . $commentRow['commentDate'] . '</td>';
                echo '<td>' . $commentRow['userName'] . '</td>';
                echo '<td>' . $commentRow['commentText'] . '</td>';
                echo '<td><form action = "deletecomment" method = "post">';
                    echo '<input type = "hidden" name = "topicID" value = "' . $_GET['id'] . '" />';
                    echo '<input type = "hidden" name = "topicVersion" value = "' . $_GET['ver'] . '" />';
                    echo '<input type = "hidden" name = "commentID" value = "' . $commentRow['commentID'] . '" />';
                    echo '<input type = "submit" value = "' . $this->translate( 'löschen') . '" />';
                echo '</form></td></tr>';
            }
            echo '</table>';
            
            echo '<form action = "showcomments?id=' . $_GET['id'] . '&ver=' . $this->selectedTopicVersion . '&page=1" method = "post">';
                echo '<input type = "submit" value = "' . $this->translate( 'zeige alle') . '" />';
            echo '</form>';
        }
        echo '<p>' . $this->createCommentForm;
        echo '</div>';
    }
?>
