<script type = "text/javascript">
/**
 * asks the user if he really want to delete this friend
 */
function confirmation()
{
    var answer = confirm( '<?php echo $this->translate( 'Sind Sie sicher, dass Sie diesen Freund endgültig löschen möchten?'); ?>');
    if ( answer)
    {
        document.forms['deleteFriend'].submit();
    }
}
</script>
<table>
	<tr>	<!-- User Information -->
		<td width="250">	
			<h2><?php echo $this->first_name ?> <?php echo $this->last_name ?></h2>
			<?php echo $this->email ?><br>
		</td>
		<td>
			<?php
			if($this->job)
			{
				echo "<b>Job: </b> ".$this->job."<br>";
			}
			if($this->adresse)
			{
				echo "<b>Adresse: </b> ".$this->adresse."<br>";
			}
			?>
		</td>
	</tr>
</table>
<?php
//User-Topic information
if($this->sizeTopics == 0 && $this->sizeInvite == 0)
{
?>
<?php echo $this->translate( 'Dieser Freund ist noch zu keinem Thema eingeladen'); ?><br>
<?php
}
else
{
?>
	<table border = "1">
		<tr>				<!--tablehead-->
			<td>
				<?php echo $this->translate( 'Thema'); ?>
			</td>
			<td>
				<?php echo $this->translate( 'sein Nick'); ?>
			</td>
			<td>
			</td>
		</tr>
	<?php
	//Invite
	if($this->sizeInvite != 0)
	{
	?>
		<tr>				<!--invite-->
			<td>
				<form name = "invitation" action="<?php echo $this->url(array('controller'=>'master', 'action'=>'send'), null, true) ?>" method="post">
            			<select name="topicID">
				<?php   
            			for($i=0; $i<$this->sizeInvite; $i++)
				{
					echo '<option value = "'. $this->infoInviteID[$i] .'">'. $this->infoInviteName[$i] .'</option>';
					
				}        
				?>
            			</select>
			</td>
			<td>
			</td>
			<td>
				<input type = "hidden" name = "toUser" value = "<?php echo $this->userID ?>" />
				<input type = "hidden" name = "<?php echo $this->userID ?>" value = "<?php echo $this->email ?>" />
				<input type = "submit" value = "<?php echo $this->translate( 'einladen') ?>" />
				</form>
			</td>
		</tr>
	<?php
	}
	//Topics
	for($i=0; $i<$this->sizeTopics; $i++)
	{
	?>
		<tr>				<!--topics-->
			<td>
				<?php echo $this->infoTopicNames[$i] ?>
			</td>
			<td>
				<?php echo $this->infoUserNames[$i] ?>
			</td>
			<td>    <!-- disconnect button  -->
				<form action="<?php echo $this->url(array('controller'=>'master', 'action'=>'lockfriend'), null, true) ?>" method="post">
					<input type = "hidden" name = "userID" value = "<?php echo $this->userID ?>" />
					<input type = "hidden" name = "topicID" value = "<?php echo $this->infoTopicIDs[$i] ?>" />
					<input type="submit" name="button_cut" value="<?php echo $this->translate( 'Trennen'); ?>" class="button" />
				</form>
			</td>
		</tr>
	<?php
	}
	?>
</table>
<?php
}
?>

<?php 
    // create friend formular
    echo $this->createFriendForm;
?>

<!-- delete button  -->
<form name = "deleteFriend" action="<?php echo $this->url(array('controller'=>'master', 'action'=>'delfriend'), null, true) ?>" method="post">
	<input type = "hidden" name = "userID" value = "<?php echo $this->userID ?>" />
	<input type="button" name="button_delete_friend" value="<?php echo $this->translate( 'Freund entfernen'); ?>" onclick = "confirmation()" />
</form>
<!-- return button  -->
<form action="<?php echo $this->url(array('controller'=>'master', 'action'=>'friend'), null, true) ?>" method="post">
	<input type="submit" name="button_back" value="<?php echo $this->translate( 'zurück'); ?>" class="button" />
</form>
