<?php 

    if ( empty( $this->commentRowSet))
    {
        $this->_redirect('showtopics?id=' . $_GET['id'] . '&ver=' . $_GET['ver']);
    }
    
    echo '<table border = "1">';
    foreach( $this->commentRowSet as $commentRow)
    {
        echo '<tr><td>' . $commentRow['commentDate'] . '</td>';
        echo '<td>' . $commentRow['userName'] . '</td>';
        echo '<td>' . $commentRow['commentText'] . '</td>';
        echo '<td><form action = "deletecomment" method = "post">';
                    echo '<input type = "hidden" name = "topicID" value = "' . $_GET['id'] . '" />';
                    echo '<input type = "hidden" name = "topicVersion" value = "' . $_GET['ver'] . '" />';
                    echo '<input type = "hidden" name = "commentID" value = "' . $commentRow['commentID'] . '" />';
                    echo '<input type = "submit" value = "' . $this->translate( 'löschen') . '" />';
                echo '</form></td></tr>';
    }
    echo '</table>Seite: ';
    
    for( $i = 1; $i <= $this->pageNumber; $i++)
    {
        if ( $i == $_GET['page'])
        {       
            echo ' ' . $i;
        }
        else
            echo ' <a href="' . $this->url(array('controller'=>'master', 'action'=>'showcomments'), null, true) . '?id=' . $_GET['id'] . '&ver=' . $_GET['ver'] . '&page=' . $i . '">' . $i . '</a>';
    }
?>

<form action = "showtopics" method = "get">
    <input type = "hidden" name = "id" value = "<?php echo $_GET['id'] ?>" />
    <input type = "hidden" name = "ver" value = "<?php echo $_GET['ver'] ?>" />
    <input type = "submit" value = "<?php echo $this->translate( 'zurück'); ?>" />
</form>
    
    
    