<!-- after the topic is created -->
<center>
    <b> <?php echo $this->translate( 'Ihr Thema wurde erfolgreich erstellt.'); ?> </b>
</center>
<!-- button to the topic -->
<?php 
echo '<form action = "showtopics?id=' . $this->topicID . '&ver=' . $this->version . '" method = "post">';
?>
    <input type = "submit" value = "<?php echo $this->translate( 'Zum Thema'); ?>" />
</form>
<!-- button to invitation -->
<form action = "invite" method = "post">
    <input type = "hidden" name = "topicID" value = "<?php echo $this->topicID ?>" />
    <input type = "submit" value = "<?php echo $this->translate( 'Einladungen versenden'); ?>" />
</form>

