<?php 
	// the doctype is from Bootstrap
	echo $this->doctype(); 
?>
 
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
<head>
 
<?php
	// declared in the Bootstrap
	echo $this->headTitle();
	echo $this->headMeta();
	echo $this->headLink();
	
?>

</head>
<body>

	<!-- in main_page are all presentation components how main_head, main_menue and main_main-->
	<div id = "main_Page">
		
		<!-- in main_head is the project title-->
		<div id = "main_Head">
			<center><h1>Webressourcen<?php echo $this->escape($this->title); ?></h1></center>
				
				<div id = "Nav">
						<!-- menu -->
						
						<a class = "navlink" href="<?php echo $this->url(array('controller'=>'', 'action'=>''), null, true); ?>">Hauptseite</a> - 
						<a class = "navlink" href="<?php echo $this->url(array('controller'=>'master', 'action'=>'index'), null, true); ?>">Masterseite</a> - 
						<a class = "navlink" href="<?php echo $this->url(array('controller'=>'friend', 'action'=>'index'), null, true); ?>">Friendseite</a> - 
						<a class = "navlink" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>">-</a>
				</div>
				
		</div>
		
		
		
		<!-- in main_menue are the topictitle to select-->
		<div id = "main_Menue">
            <ul>
                <?php
                    foreach( $this->topicList as $topic)
                    {
                        if ( isset( $_GET['id']))
                        {
                            if ( $_GET['id'] == $topic['topicID'])
                            {
                                echo '<li>aktuelles Thema</li>';
                            }
                            else 
                            {
                                echo '<li><a href="http://localhost/Webressourcen/public/master/showtopics?id='.$topic['topicID'] . '&ver=1">';
                                echo $topic['topicName'].'</a></li>';
                            }
                        }
                        else 
                        {
                            echo '<li><a href="http://localhost/Webressourcen/public/master/showtopics?id='.$topic['topicID'] . '&ver=1">';
                            echo $topic['topicName'].'</a></li>';
                        }
                    }
                ?>
            </ul>
		</div>
		
		<!-- in main_main are the active action methode -->
		<div id = "main_Main">
			<?php
				//-- import Mainpage
				echo $this->layout()->content;
			?>
		</div>
		<div id = "footer">
            Webressourcen 2012
        </div>
	</div>
</body>
</html>
