<?php echo $this->doctype(); ?>
<html>
	<head> 
		<?php
		echo $this->headMeta();//for umlaute from Bootstrap.php
		echo $this->headLink();//for .css    from Bootstrap.php
		?>
	</head>
	<body>
		<div id="page">
		 
			<div id="header">
				<center><h1>BComments<?php echo $this->escape($this->title); ?></h1></center>
			</div>
			 
			<div id="main">
			 
				<div id="navi">
					<ul>
					<li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>">Hauptseite</a></li>
					<li><a href="<?php echo $this->url(array('controller'=>'comments', 'action'=>'index'), null, true); ?>">Themen</a></li>
					</ul>
				</div>
				 
				<div id="content">
					<?php
					//-- Hauptseite einbinden --
					echo $this->layout()->content;
					?>
				</div>
			 
			</div>
			 
			<div id="footer">
			BComments 2012
			</div>
		 
		</div>
	</body>
</html>
