<?php echo $this->doctype(); ?>
<!-- basic structure of the website -->
<html>
	<head> 
		<?php
		echo $this->headMeta();//for umlaute from Bootstrap.php
		echo $this->headLink();//for .css    from Bootstrap.php
		?>
		<title>BComment<?php echo $this->escape($this->title); ?></title>
	</head>
	<body>
		<div id="page">
			<!-- headline -->
			<div id="header">
				<center><h1>BComment<?php echo $this->escape($this->title); ?></h1></center>
			</div>
			<!-- main part --> 
			<div id="main">
				<!-- navigation with links to mainpage or topic overview -->
				<div id="navi">
					<ul>
					<li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index'), null, true); ?>">Hauptseite</a></li>
					<li><a href="<?php echo $this->url(array('controller'=>'comments', 'action'=>'index'), null, true); ?>">Themen</a></li>
					</ul>
				</div>
				<!-- content of the particular page --> 
				<div id="content">
					<?php
					//-- integrate page --
					echo $this->layout()->content;
					?>
				</div> 
			</div>
			<!-- footer --> 
			<div id="footer">
			BComment 2012
			</div>
		 
		</div>
	</body>
</html>
