<?php

	//Title---------------------------------------------------
	echo "<div id = \"FriendShowTopicTitel\" >";
	echo $this->escape($this->friendTopicTitel);
	echo "</div>";
	
	//select TopicVersion--------------------------------------
	echo "<table id = \"FriendShowTopicVersionTable\" border = \"1\" >";
		echo "<tr>";
		
        //Version Tittel
        echo "<td>";
           echo $this->escape($this->versionTitle); 
        echo "</td>";
        
		//leftoperator----------
		
		if($this->escape($this->currentPageNavigator) > 0)
		{
			echo "<td>";
				echo 	"<form action =\"showtopic\" method = \"get\">
							<input type =\"hidden\" name = \"PageNavigator\" value = \"".($this->escape($this->currentPageNavigator)-1)."\" />
							<input type=\"submit\" class=\"FriendPageButton\" value = \"<-\" />
						</form>";
			echo "</td>";
		}
		
		//selector Page
		foreach($this->version as $v)
		{
			echo "<td>";
				echo 	"<form action =\"showtopic\" method = \"get\">
							<input type =\"hidden\" name = \"topicVersion\" value = \"".($this->escape($v))."\" />";
                            
                            if(($this->escape($this->currentTopicVersion)) == ($this->escape($v)))
                            {
                            
                                echo "<input type=\"submit\" class=\"FriendPageButton\" value = \"[".($this->escape($v))."]\" />";
                            }
                            else
                            {
                                echo "<input type=\"submit\" class=\"FriendPageButton\" value = \"".($this->escape($v))."\" />";
                            }
				echo		"</form>";
			echo "</td>";
		}
		
		//rightoperator----------
		
		if($this->escape($this->currentPageNavigator) < $this->escape($this->numberPageNavigator))
		{
			echo "<td>";
				echo 	"<form action =\"showtopic\" method = \"get\">
							<input type =\"hidden\" name = \"PageNavigator\" value = \"".($this->escape($this->currentPageNavigator)+1)."\" />
							<input type=\"submit\" class=\"FriendPageButton\" value = \"->\" />
						</form>";
			echo "</td>";
		}

		
	
		echo "</tr>";
	echo "</table>";
	
    //Topic---------------------------------------------------
	echo  "<iframe src=\"topicview?id= ".($this->escape($this->topicID)) ." &ver= ". ($this->escape($this->currentTopicVersion)) . "\" width=\"90%\" height=\"400\" name=\"Topic\"></iframe></br>";
    echo $this->escape($this->topicSource). "\n";
    
    //Topic assessment-------------------------------------------------
    
    
	//Comment--------------------------------------------------
	echo "<table id = \"FriendShowTopicCommentTable\" border = \"1\" >";
	
	//Table tiltel
	echo "<tr>";
		echo "<th>";
		echo	"<form action =\"showcomment\" method = \"get\">
					<input type=\"submit\" class=\"FriendButtonTableHeadLink\" value = \"All Comment\" />
				</form>";
				
		echo	"<form action =\"create\" method = \"get\">
					<input type=\"submit\" class=\"FriendButtonTableHeadCreate\" value = \"Add Comment\" />
				</form>";
        echo	"<form action =\"createname\" method = \"get\">
					<input type=\"submit\" class=\"FriendButtonTableHeadCreateName\" value = \"Update Name\" />
				</form>";
		echo "</th>";
	echo "</tr>";
	//Table body
	

	foreach($this->friendComment as $row)
	{
    
		echo "<tr>";
			echo "<td>"; // comment Titel: username, userdate , delete
			
				//view the UserName
				//the user can be anonymous
				if(false == $this->escape($row["anonymous"]))
				{
					echo "<div id = \"FriendShowTopicTableUserName\">".$this->escape($row["userName"])."</div>"; 
				}
				else
				{
					echo "<div id = \"FriendShowTopicTableUserName\">anonymous</div>"; 
				}

				echo "<div id = \"FriendShowTopicTableCommentDate\">".$this->escape($row["commentDate"])."</div>"; //view the commentDate
				
				//Delete
				//the user can his own comment delete
				if( $this->escape($row["userID"]) == $this->escape($this->userID))
				{
					echo 	"<form action =\"showtopic\" method = \"post\">
								<input type =\"hidden\" name = \"CommentID\" value = \"".$this->escape($row["commentID"])."\" />
								<input type=\"submit\" class=\"FriendButtonDelete\" value = \"Delete\" />
							</form>";
				}
			echo "</td>";
		echo "</tr>";
	
		echo "<tr>";	//the Comment
			echo "<td>";
				echo "<div id = \"FriendShowTopicTableCommentDate\">".$this->escape($row["commentText"])."</div>";
			echo "</td>";
		echo "</tr>";
	
		
	}
	
	echo "</table>";
	
	/*
		css name:	FriendShowTopicTitel : is the title of the topic
					FriendShowTopicCommentTable : is the Tabel from the Coment
					FriendButtonTableHeadLink : is the Button go to All Comments
					FriendButtonTableHeadCreate : is the Button go to Add Comment
					FriendShowTopicTableUserName : is the user name in the Comment table
					FriendShowTopicTableCommentDate: is the user datetime in the Comment table
					FriendButtonDelete : is the Delete Button from a Comment
					
		
	*/
		
	
?>